// <auto-generated />
using ArabalarDunyasii.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArabalarDunyasii.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    [Migration("20211107165206_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ArabalarDunyasii.Models.Araba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Yil")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Arabalar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Model = "Volkswagen Passat 1.6 TDI BlueMotion ComfortLine",
                            Yil = 2018
                        },
                        new
                        {
                            Id = 2,
                            Model = "Seat Ibiza 1.6 Stella",
                            Yil = 2001
                        },
                        new
                        {
                            Id = 3,
                            Model = "Renault Fluence 1.5 dCi Authentique",
                            Yil = 2011
                        },
                        new
                        {
                            Id = 4,
                            Model = "Seat Leon 1.6 TDI CR Style",
                            Yil = 2014
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
